[environment]
mode = "dev" # "dev", "prod"

[data] # relative to cwd
upload_dir = "../data/uploads"

[dev]
host = "localhost" # the host to run the frontend on in dev mode
port = 1600 # the port to run the frontend on in dev mode. use nginx to redirect requests here
log_level = 10 # the log level to use in dev mode
# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# WARN = WARNING
# INFO = 20
# DEBUG = 10
# NOTSET = 0

[prod]
host = "localhost" # the host to run the frontend on in prod
port = 1600 # the port to run the frontend on in prod. use nginx to redirect requests here
log_level = 20 # the log level to use in prod
# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# WARN = WARNING
# INFO = 20
# DEBUG = 10
# NOTSET = 0

[logging]
file = "../data/main.log" # the file to use for logging

[discord]
invite_url = "https://dsc.gg/cuhhubsw" # invite link to cuhhub discord server. used for `/` redirect